language: php
php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
script:
  - mkdir -p build/logs
  - phpunit
after_success:  
  - travis_retry php vendor/bin/coveralls -v
